# -*- coding: utf-8 -*-
# This file was generated by Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import ctypes
import sys
import numpy as np
import matplotlib
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

from logic import *

# Explicit imports to satisfy Flake8
from tkinter import (
    BooleanVar,
    messagebox,
    Button,
    Canvas,
    Checkbutton,
    Entry,
    Frame,
    Label,
    Listbox,
    PhotoImage,
    Radiobutton,
    StringVar,
    Text,
    Tk,
    ttk,
)

try:
    from PIL import Image, ImageTk
except ImportError:
    Image = None
    ImageTk = None

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")
THEME = ""
IMAGE_REFS = []


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def set_assets_path(path: str):
    global ASSETS_PATH
    ASSETS_PATH = OUTPUT_PATH / Path(path)


def load_photo_image(path: str):
    try:
        image = PhotoImage(file=path)
    except Exception:
        if Image is None or ImageTk is None:
            raise
        image = ImageTk.PhotoImage(Image.open(path))
    IMAGE_REFS.append(image)
    return image


def enable_dpi_awareness():
    if sys.platform != "win32":
        return
    try:
        ctypes.windll.shcore.SetProcessDpiAwareness(1)
    except Exception:
        try:
            ctypes.windll.user32.SetProcessDPIAware()
        except Exception:
            pass


def center_window(window, width, height):
    window.update_idletasks()
    x = int((window.winfo_screenwidth() - width) / 2)
    y = int((window.winfo_screenheight() - height) / 2)
    window.geometry(f"{width}x{height}+{x}+{y}")


def create_rounded_rectangle(canvas, x1, y1, x2, y2, radius, **kwargs):
    radius = max(0, min(radius, abs(x2 - x1) / 2, abs(y2 - y1) / 2))
    if radius == 0:
        return canvas.create_rectangle(x1, y1, x2, y2, **kwargs)
    points = [
        x1 + radius, y1,
        x2 - radius, y1,
        x2, y1,
        x2, y1 + radius,
        x2, y2 - radius,
        x2, y2,
        x2 - radius, y2,
        x1 + radius, y2,
        x1, y2,
        x1, y2 - radius,
        x1, y1 + radius,
        x1, y1,
    ]
    return canvas.create_polygon(points, smooth=True, **kwargs)


class ImageButton(Label):
    def __init__(self, master=None, command=None, **kwargs):
        super().__init__(master, **kwargs)
        self._command = command
        self.configure(cursor="hand2")
        self.bind("<Button-1>", self._invoke)

    def _invoke(self, event):
        if self._command is not None:
            self._command()

    def configure(self, cnf=None, **kwargs):
        if cnf and "command" in cnf:
            cnf = dict(cnf)
            self._command = cnf.pop("command")
        if "command" in kwargs:
            self._command = kwargs.pop("command")
        return super().configure(cnf, **kwargs)

    config = configure


def apply_theme(window):
    if not THEME:
        return
    try:
        ttk.Style(window).theme_use(THEME)
    except Exception:
        pass


enable_dpi_awareness()

window = Tk()
apply_theme(window)

window.geometry("1200x600")
window.configure(bg="#FFFFFF")
center_window(window, 1200, 600)


canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=600,
    width=1200,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
image_image_1 = load_photo_image(
    relative_to_assets("element_1.png"))
image_1 = canvas.create_image(
    938.9999737731671,
    304.9999999562886,
    image=image_image_1
)

figura = Figure((7.4, 5), 100)
fig_canvas = FigureCanvasTkAgg(figura)

def graficar(tiempos, valores_raw, valores_filtrados, picos_idx, bpm):
    global fig_canvas,figura
    tiempos_picos = tiempos[picos_idx]
    picos = valores_filtrados[picos_idx]

    fig_canvas.get_tk_widget().pack_forget()

    axes = figura.subplots(2, 1, sharex=True)

    # Panel superior: señal cruda
    axes[0].plot(tiempos, valores_raw, color="#888888", linewidth=0.7)
    axes[0].set_ylabel("ADC (cruda)")
    axes[0].set_title("Señal original")
    axes[0].grid(True, alpha=0.3)

    # Panel inferior: señal filtrada + picos
    axes[1].plot(tiempos, valores_filtrados, color="#4a90d9", linewidth=1.2)
    axes[1].scatter(tiempos_picos, picos, color="red", zorder=5, s=50)
    axes[1].set_ylabel("ADC (filtrada)")
    axes[1].set_xlabel("Tiempo (s)")
    axes[1].set_title(f"Señal filtrada — {len(picos_idx)} latidos detectados  |  ~{bpm} BPM")
    axes[1].grid(True, alpha=0.3)

    figura.tight_layout()
    fig_canvas.get_tk_widget().pack(side="left")


def capture_data():
    global conectado
    messagebox.showinfo("Info", "Manten quieto el dedo por 20 segundos.")
    bpm,tiempo,valores_raw,valores_filtrados,picos = capture(conectado)
    fc = canvas.create_text(
        1045.0,
        157.0,
        anchor="nw",
        text=str(bpm),
        fill="#000000",
        font=("Host Grotesk", 36 * -1, "normal", "roman"),
    )
    r= canvas.create_rectangle(
        (1045,157,1200,200),
        fill="white",
        outline="white")
    canvas.tag_lower(r, fc)

    graficar(tiempo, valores_raw,valores_filtrados,picos, bpm)


button_image_1 = load_photo_image(
    relative_to_assets("button_1.png"))
button_1 = ImageButton(
    window,
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=capture_data,
    relief="flat"
)

button_1.place(
    x=975.0,
    y=375.0,
    width=189.0,
    height=64.0
)

canvas.create_text(
    996.0,
    125.0,
    anchor="nw",
    text="FC promedio:",
    fill="#000000",
    font=("Host Grotesk", 24 * -1, "normal", "roman")
)

canvas.create_text(
    1045.0,
    157.0,
    anchor="nw",
    text="NA",
    fill="#000000",
    font=("Host Grotesk", 36 * -1, "normal", "roman")
)

canvas.create_text(
    272.0,
    268.0,
    anchor="nw",
    text="No hay datos por mostrar, da click\nen “Captura Datos” para iniciar",
    fill="#000000",
    font=("Host Grotesk", 24 * -1, "normal", "roman")
)
window.resizable(False, False)

conectado = connect()

def connected():
    canvas.create_rectangle(
        950.0,
        5.0,
        1187.0,
        42.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        1021.0,
        14.0,
        anchor="nw",
        text="Arduino Conectado",
        fill="#000000",
        font=("Host Grotesk", 15 * -1, "normal", "roman")
    )

    image_image_2 = load_photo_image(relative_to_assets("element_2.png"))
    image_2 = canvas.create_image(
        1000,
        24,
        image=image_image_2
    )


def try_connect():
    connected_status = connect()
    if connected_status:
        connected()
        print(connected_status)

if not conectado:
    messagebox.showerror("Error", "Arduino no conectado")
    button_image_2 = load_photo_image(
        relative_to_assets("button_2.png"))
    button_2 = ImageButton(
        window,
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=try_connect,
        relief="flat"
    )
    button_2.place(
        x=950.0,
        y=5.0,
        width=237.0,
        height=37.0
    )
else:
    connected()

if __name__ == "__main__":
    window.mainloop()